export const VERBS: readonly string[] = [
	"thinking",
	"chiseling",
	"reading",
	"sketching",
	"hauling",
	"gathering",
	"hammering",
	"polishing",
	"spelunking",
	"tracing",
	"weighing",
	"measuring",
	"sifting",
	"stitching",
	"weaving",
	"binding",
	"surveying",
	"mapping",
	"plotting",
	"hunting",
	"foraging",
	"compiling",
	"refining",
	"smelting",
	"forging",
	"tempering",
	"navigating",
	"orbiting",
	"steering",
	"caching",
	"coalescing",
	"crystallizing",
	"chaining",
	"branching",
	"unspooling",
	"settling",
	"converging",
	"sharpening",
	"shaping",
	"summoning",
];

export function nextVerb(index: number): string {
	return VERBS[index % VERBS.length];
}
